apiVersion: sro.openshift.io/v1alpha1
kind: SpecialResource
metadata:
  name: REPLACE_SPECIALRESOURCE
  namespace: REPLACE_NAMESPACE
spec:
  driverContainer:
    source:
      git:
        ref: "master"
        uri: "https://github.com/kmods-via-containers/kmods-via-containers"
    
