apiVersion: apps/v1
kind: Deployment
metadata:
  name: special-resource-operator
  namespace: REPLACE_NAMESPACE
spec:
  replicas: 1
  selector:
    matchLabels:
      name: special-resource-operator
  template:
    metadata:
      labels:
        name: special-resource-operator
    spec:
      serviceAccountName: special-resource-operator
      containers:
        - name: special-resource-operator
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
          - special-resource-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "special-resource-operator"
      nodeSelector:
        node-role.kubernetes.io/master: ""
      tolerations:
        - key: "node-role.kubernetes.io/master"
          operator: "Equal"
          value: ""
          effect: "NoSchedule"



