apiVersion: sro.openshift.io/v1alpha1
kind: SpecialResource
metadata:
  name: REPLACE_SPECIALRESOURCE
  namespace: REPLACE_NAMESPACE
spec:
  driverContainer:
    source:
      git:
        ref: "ppc64le_support"
        uri: "https://gitlab.com/benswinney/driver.git"
    buildArgs: 
    - name: "DRIVER_VERSION"
      value: "440.64.00"
  node:
    selector: "feature.node.kubernetes.io/pci-10de.present"
    
