apiVersion: sro.openshift.io/v1alpha1
kind: SpecialResource
metadata:
  name: REPLACE_SPECIALRESOURCE
  namespace: REPLACE_NAMESPACE
spec:
  driverContainer:
    source:
      git:
        ref: "master"
        uri: "https://github.com/openshift-psap/kvc-simple-kmod.git"
    buildArgs:
    - name: "KVER"
      value: "{{.KernelVersion}}"
    - name: "KMODVER"
      value: "SRO"

  dependsOn: 
  - name: "driver-container-base"
    namespace: "driver-container-base"

    




